language: python

sudo: required

services:
  - docker

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  # show all available docker versions
  - apt-cache madison docker-engine
  - docker --version

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib; fi
  - pip install -r requirements-dev.txt
  - pip install codecov
  - pip install -e .

script:
  - coverage run --source wharfee -m py.test
  - cd tests
  - behave

after_success:
  - codecov
