language: python

dist: jammy

sudo: required

services:
  - docker

python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"

before_install:
  # show docker version
  - docker --version

install:
  - pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - pip install codecov
  - pip install -e .

script:
  - coverage run --source wharfee -m py.test
  - cd tests
  - behave --tags ~@slow

after_success:
  - codecov
