build: false

environment:
  matrix:
    - PYTHON: "C:\\Python310"
      PYTHON_VERSION: "3.10"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python311"
      PYTHON_VERSION: "3.11"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python312"
      PYTHON_VERSION: "3.12"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python313"
      PYTHON_VERSION: "3.13"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\Scripts\pip.exe install -r requirements-win.txt"
  - "%PYTHON%\Scripts\pip.exe install ."

test_script:
  - "%PYTHON%/Scripts/py.test"
